# Generated by Django 3.2.16 on 2022-12-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221207_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Custumer',
        ),
    ]
