# Generated by Django 3.2.16 on 2022-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
